using System;
using System.Collections.Generic;

namespace TheCoreBanking.Customer.Data.Models
{
    public partial class TblBankingcustomers
    {
        public int Id { get; set; }
        public string Ccode { get; set; }
        public string CusTypeS { get; set; }
        public string Ctname { get; set; }
        public DateTime? Ccdate { get; set; }
        public string Csname { get; set; }
        public string Cname { get; set; }
        public string Cfname { get; set; }
        public string Ctitle { get; set; }
        public string Cguardian { get; set; }
        public DateTime? Cdob { get; set; }
        public string Cpob { get; set; }
        public string Cmstatus { get; set; }
        public string Cgender { get; set; }
        public string Cnbusiness { get; set; }
        public string Ccoi { get; set; }
        public string Crazip { get; set; }
        public string Chphone { get; set; }
        public string Cmphone { get; set; }
        public string Cracountry { get; set; }
        public string Cpastate { get; set; }
        public string Cpacity { get; set; }
        public string CmodeofId { get; set; }
        public string Cpobox { get; set; }
        public string Cpemail { get; set; }
        public string Cpanationality { get; set; }
        public string Ccoresidence { get; set; }
        public string CcontactMeans { get; set; }
        public string Crelationship { get; set; }
        public string CmaidenName { get; set; }
        public string Cnoksname { get; set; }
        public string Cnokfname { get; set; }
        public string Cnokphone { get; set; }
        public string Coccupation { get; set; }
        public string Cnoemployer { get; set; }
        public string CemployAddress { get; set; }
        public string CemployState { get; set; }
        public string CemployCountry { get; set; }
        public string CofPhone { get; set; }
        public string Ctid { get; set; }
        public string Miscode { get; set; }
        public string Branch { get; set; }
        public string Company { get; set; }
        public string CustomerPic { get; set; }
        public string CustomerSign { get; set; }
        public string CustomerThumb { get; set; }
        public int? WedDay { get; set; }
        public string WedMonth { get; set; }
        public int? WedYear { get; set; }
        public string Ccocontact { get; set; }
        public string Cnob { get; set; }
        public string Csector { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
        public string Field6 { get; set; }
        public string Field7 { get; set; }
        public string Field8 { get; set; }
        public string Field9 { get; set; }
        public string Field10 { get; set; }
        public string Misstaff { get; set; }
        public string CpType { get; set; }
        public string ShortCode { get; set; }
        public string AccountType { get; set; }
        public string Ccategory { get; set; }
        public string AccountTypeDesc { get; set; }
        public string Bank { get; set; }
        public string Ctarget { get; set; }
        public bool? Approved { get; set; }
        public bool? Disapproved { get; set; }
        public DateTime? DateApproved { get; set; }
        public string ApprovedBy { get; set; }
        public string Nokaddress { get; set; }
        public string Nokemail { get; set; }
        public string Scumol { get; set; }
        public string GuardianPhone { get; set; }
        public string GuardianAddr { get; set; }
        public bool? MailSent { get; set; }
        public bool? Pfacustomer { get; set; }
        public string Field11 { get; set; }
        public string Field12 { get; set; }
        public string Field13 { get; set; }
        public string Field14 { get; set; }
        public string Field15 { get; set; }
        public string Field16 { get; set; }
        public string Field17 { get; set; }
        public string Field18 { get; set; }
        public string Field19 { get; set; }
        public string Field20 { get; set; }
        public string CoyWebsite { get; set; }
        public string Email2 { get; set; }
        public string CreditRating { get; set; }
        public DateTime? CmodeofIddate { get; set; }
        public DateTime? CreateDate { get; set; }
        public string Lga { get; set; }
        public string PermitNo { get; set; }
        public string EducationLevel { get; set; }
        public DateTime? CertificationDate { get; set; }
        public DateTime? EmployDate { get; set; }
        public string PreviousEmployer { get; set; }
        public string MotherName { get; set; }
        public string FirstChild { get; set; }
        public DateTime? ChildDob { get; set; }
        public string RegisteredOffice { get; set; }
        public string CorrespondenceAddr { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string BankAccount { get; set; }
        public string PrevCreditRating { get; set; }
        public string AnnualTurnOver { get; set; }
        public string RcrelatedCoy { get; set; }
        public string RcparentBody { get; set; }
        public string GeoRegion { get; set; }
        public string FingerPrintId { get; set; }
        public string CorporateBizCategory { get; set; }
        public string HomeTown { get; set; }
        public string Spouse { get; set; }
        public string IssuePlace { get; set; }
        public string IssueAuthority { get; set; }
        public string IndAcctsWithBanks { get; set; }
        public string IndFund { get; set; }
        public decimal? IndFundAmt { get; set; }
        public bool? Political { get; set; }
        public bool? AccountComplete { get; set; }
        public string TypeOfAccount { get; set; }
        public string SortCode { get; set; }
        public DateTime? DateAccountOpened { get; set; }
        public DateTime? Nokdob { get; set; }
        public string NokGender { get; set; }
        public string SpousePhone { get; set; }
        public string SpouseEmail { get; set; }
        public string EmploymentStatus { get; set; }
        public string ExpectedIncome { get; set; }
    }
}
